version: '3.8'

services:
  bot:
    build: .
    container_name: anime_filter_bot
    restart: always
    env_file:
      - .env
    ports:
      - "10000:10000"
    volumes:
      - .:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: anime_bot_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
